### ISSUE TITLE
Side scrolling on Desktop.

### ISSUE THREAD

**Issue by Leroy-sama** [josh76543210/Frontend-collaboration-landing-page#10]
The landing image is very big which has caused side scrolling.
![image](https://github.com/josh76543210/Frontend-collaboration-landing-page/assets/113260290/d03c89f3-4f6a-4cae-aa61-b3c48de6f48c)

**Comment by Leroy-sama** [comment]
You can see the horizontal scroll bar on the screenshot

**Comment by josh76543210** [comment]
Fixed with PR #11
